apiVersion: v1
kind: Service
metadata:
  name: {{ include "snmpsim.fullname" . }}
  labels:
    {{- include "snmpsim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 161
      protocol: UDP
      name: snmp
  selector:
    {{- include "snmpsim.selectorLabels" . | nindent 4 }}
